In [56]:
import numpy as np

In [57]:
a = np.array([1,2,3,4]) # 1-D / vector
a

array([1, 2, 3, 4])

In [58]:
a.shape

(4,)

In [59]:
a.ndim #array 1-D

1

In [60]:
type(a)

numpy.ndarray

In [61]:
b = np.array([[1,1,2,3],
              [3,5,6,7]])
b

array([[1, 1, 2, 3],
       [3, 5, 6, 7]])

In [62]:
b.shape

(2, 4)

In [63]:
type(b)

numpy.ndarray

In [64]:
b.ndim #2-D array

2

In [65]:
c = np.array([[[1,1,2,3],
              [3,5,6,7],
              [3,4,5,6.3]]])
c

array([[[1. , 1. , 2. , 3. ],
        [3. , 5. , 6. , 7. ],
        [3. , 4. , 5. , 6.3]]])

In [66]:
c.shape

(1, 3, 4)

In [67]:
type(c)

numpy.ndarray

In [68]:
c.ndim

3

In [69]:
 a.dtype, b.dtype, c.dtype

(dtype('int32'), dtype('int32'), dtype('float64'))

In [70]:
a.nbytes , b.nbytes , c.nbytes  #total bytes consumed by the elements of an array

(16, 32, 96)

In [71]:
a.size, b.size, c.size  #determine how many elements are there in an array

(4, 8, 12)

array creation
